[package]
name = "fixnum"
version = "0.2.0"
description = "fixed-point numbers"
keywords = ["fixed", "decimal", "numbers"]
authors = ["Paul Loyd <pavelko95@gmail.com>"]
repository = "https://github.com/loyd/fixnum"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
categories = ["no-std"]

[[bench]]
name = "fixed_point"
path = "benches/fixed_point.rs"
harness = false

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
typenum = "1.12.0"
derive_more = { version = "0.99.9", default-features = false, features = ["display"] }

[dev-dependencies]
anyhow = "1.0.29"
criterion = "0.3.3"

[features]
default = ["std", "serde"]
std = ["derive_more/error"]
i128 = []
