[package]
name = "fixnum"
version = "0.1.0"
description = "fixed-point numbers"
keywords = ["fixed", "decimal", "numbers"]
repository = "https://github.com/loyd/fixnum.rs"
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[[bench]]
name = "fixed_point"
path = "benches/fixed_point.rs"
harness = false

[dependencies]
thiserror = "1.0.11"
serde = { version = "1.0", features = ["derive"] }
typenum = "1.12.0"
uint = "0.8.5"

[dev-dependencies]
anyhow = "1.0.29"
criterion = "0.3.3"
