[package]
name = "fixed_point"
version = "0.0.0"
publish = ["zubr"]
edition = "2018"

[dependencies]
thiserror = "1.0.11"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.29"
